import axios from "axios";
import Head from "next/head";
import { useState } from "react";
import { BsSearch } from "react-icons/bs";
import Spinner from "../components/Spinner";
import Weather from "../components/Weather";

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
      console.log(response.data);
    });
    setCity("");
    setLoading(false);
  };

  if (loading) {
    return <Spinner />;
  } else {
    return (
      <div className="bg-gray-100 min-h-screen">
        <Head>
          <title>Weather - Next.JS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <div className="flex w-full justify-center items-center">
            <form
              action=""
              onSubmit={fetchWeather}
              className="border-2 border-gray-600 px-4 py-2 rounded-lg flex space-x-2 mt-5"
            >
              <div>
                <input
                  className="outline-none border-0 ring-0 bg-transparent"
                  type="text"
                  placeholder="Search City"
                  onChange={(e) => setCity(e.target.value)}
                />
              </div>
              <button>
                <BsSearch onClick={fetchWeather} size={20} />
              </button>
            </form>
          </div>
          {weather.main ? (
            <Weather data={weather} />
          ) : (
            <>
              <h3 className="text-lg font-bold text-center">
                Input the city name to see the weather
              </h3>
            </>
          )}
        </main>
      </div>
    );
  }
}
